#!/usr/bin/env python3
"""NNUE/tools/make_local.py -- wrap the inspector as a standalone .html.

    python3 NNUE/tools/make_local.py

nnue_inspector.html is page CONTENT: no doctype, no <html>/<head>/<body>,
because the artifact host supplies those. Opened straight off disk that same
file still renders, but in QUIRKS MODE and with no charset or viewport
declaration -- which is the sort of difference that shows up as one subtly
wrong margin and wastes an hour.

So the local copy is generated rather than maintained: one source, no drift.
Re-run this after any edit to nnue_inspector.html.
"""

import os
import re
import sys

TOOLS = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(TOOLS, "nnue_inspector.html")
OUT = os.path.join(TOOLS, "nnue_inspector_local.html")

SKELETON = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- GENERATED by NNUE/tools/make_local.py from nnue_inspector.html.
     Edit that file, then re-run the script. -->
</head>
<body>
%s
</body>
</html>
"""


def main():
    if not os.path.exists(SRC):
        sys.exit(f"make_local: {SRC} not found")
    content = open(SRC, encoding="utf-8").read()
    for tag in ("<!doctype", "<html", "<head>", "<body"):
        if tag in content.lower():
            sys.exit(f"make_local: {os.path.basename(SRC)} already contains "
                     f"'{tag}' -- it is meant to be page content only")
    if not content.isascii():
        # the content is ASCII by design so it cannot depend on a charset
        # declaration; if that ever changes the local copy still declares one,
        # but the artifact copy would break, so fail loudly here.
        sys.exit("make_local: source is no longer pure ASCII -- the artifact "
                 "copy has no charset declaration and would mojibake")
    open(OUT, "w", encoding="utf-8").write(SKELETON % content)
    title = re.search(r"<title>(.*?)</title>", content)
    print(f"wrote {os.path.relpath(OUT, os.path.dirname(TOOLS))} "
          f"({os.path.getsize(OUT) / 1024:.0f} KB"
          + (f', "{title.group(1)}"' if title else "") + ")")
    print("open it directly in a browser -- no server needed, nothing is "
          "fetched, and the net you pick never leaves the machine")


if __name__ == "__main__":
    main()
