#!/usr/bin/env python3
"""scripts/calibrate_skill.py -- what is each Skill Level worth, in Elo?

    python3 scripts/calibrate_skill.py --levels 0,10,20,30 --positions 500
    python3 scripts/calibrate_skill.py --fit skillcal_*.log

DOES SKILL LEVEL NEED RE-CALIBRATING WHEN A STRONGER VERSION SHIPS? NO.
Skill Level is defined RELATIVE to the engine it sits in -- a weakness term
plus a depth cap, not an Elo target -- so every level inherits whatever the
current engine is worth. Ship a +20 Elo version and all 41 levels get 20 Elo
stronger by construction; nothing here needs touching, and level 40 is always
exactly full strength. That self-relativity is the reason the feature is
maintenance-free and the reason it cannot honestly be labelled in Elo.

WHAT WOULD NEED RE-CALIBRATING IS UCI_Elo, which is why cuci refuses it. An
Elo mapping is a claim about ABSOLUTE strength, so it drifts upward with
every release and would have to be re-fitted EVERY time the engine gains --
a recurring obligation, not a one-time cost. Stockfish re-fits theirs. This
script is what that re-fit would run; until it has been run and the numbers
committed, UCI_Elo stays unimplemented.

WHAT IT MEASURES. Each requested level plays a match against FULL-STRENGTH
Pygin (level 40) at the standard screen instrument, so the result is
"level N is X Elo below current full strength" -- a self-relative number that
stays meaningful across versions, unlike an absolute Elo claim.

READ THE RESULT WITH THIS CAVEAT. Measured 2026-07-07 on Elo-limited
Stockfish: a real +119 Elo gap between two versions read as ~22 against the
limiter, because errors are injected at a fixed RATE and exploiting them is
nearly fixed-yield. Limited engines compress differences ~5x. So these
numbers describe the LIMITER, and must never be used to measure Pygin's own
version-over-version progress -- that is what the internal ledger is for.

This script never starts a match. It writes the shims and prints the
commands; you run them.
"""

import argparse
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHIM_DIR = os.path.join(ROOT, "NNUE", "shims")

SHIM = '''"""NNUE/shims/engine_skill{lv:02d}.py -- GENERATED by scripts/calibrate_skill.py.

Skill Level {lv} of 40 as a match-playable engine. cuci owns the shipped
implementation (it is a protocol feature); match.py drives engine classes
directly and never speaks UCI, so this re-uses cuci's OWN _skill_pick -- the
same arithmetic decides the move here and in play, or the calibration would
describe something that does not ship.

Regenerate rather than edit: scripts/calibrate_skill.py --levels {lv}
"""

import random
import sys as _sys
import os as _os
_sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.dirname(
    _os.path.abspath(__file__)))))

import cengine
import cuci

_LEVEL = {lv}


class Engine(cengine.Engine):
    USE_NNUE = True
    NNUE_FILE = "NNUE/nets/nnue_v12_bf86c4ced057.nnue"
    LAZY_NNUE = True
    TT_DEADTAG = True

    def __init__(self, *a, **kw):
        super().__init__(*a, **kw)
        self._skill_rng = random.Random()

    def _skill_move(self, board, max_depth):
        depth = max(1, min(1 + _LEVEL // 2, max_depth))
        k = max(cuci.SKILL_CANDIDATES, 1)
        lines, excl, states, total = [], [], {{}}, 0
        try:
            for _ in range(k):
                self._lib.root_exclude_clear()
                for m in excl:
                    self._lib.root_exclude_add(
                        m.from_square | (m.to_square << 6)
                        | ((m.promotion or 0) << 12))
                mv = super().get_best_move(board, depth)
                if mv is None or mv in excl:
                    break
                total += self.nodes_searched
                lines.append((mv, self.last_score))
                states[mv] = (self.last_score, self.last_pv,
                              self.last_depth or depth)
                excl.append(mv)
        finally:
            self._lib.root_exclude_clear()
        if not lines:
            return None
        chosen = cuci._skill_pick(lines, _LEVEL, self._skill_rng)
        self.last_score, self.last_pv, self.last_depth = states[chosen]
        self.nodes_searched = total
        return chosen

    def get_best_move(self, board, depth):
        return self._skill_move(board, depth)

    def get_best_move_timed(self, board, time_limit, max_depth=245):
        # The depth cap IS the limiter; the clock only bounds it.
        return self._skill_move(board, min(max_depth, 40))
'''


def write_shims(levels):
    made = []
    for lv in levels:
        path = os.path.join(SHIM_DIR, f"engine_skill{lv:02d}.py")
        with open(path, "w") as f:
            f.write(SHIM.format(lv=lv))
        made.append(path)
    return made


def fit(logs):
    """Read finished match logs and print the level -> Elo table."""
    rows = []
    for path in sorted(logs):
        m = re.search(r"skill(\d+)", os.path.basename(path))
        txt = open(path, errors="ignore").read()
        elo = re.findall(r"Engine 1 score:.*=>\s*([-+0-9.]+) \+/- ([0-9.]+) Elo", txt)
        pen = re.findall(r"^Ptnml:\s*([0-9,\s]+)$", txt, re.M)
        if not (m and elo):
            print(f"  {os.path.basename(path)}: no finished result, skipped")
            continue
        rows.append((int(m.group(1)), float(elo[-1][0]), float(elo[-1][1]),
                     sum(int(x) for x in pen[-1].replace(",", " ").split()) if pen else 0))
    if not rows:
        return
    print("\n  level   Elo vs full strength      pairs")
    for lv, e, err, pairs in sorted(rows):
        print(f"  {lv:5d}   {e:+8.2f} +/- {err:4.1f}        {pairs:,}")
    print("\n  Self-relative by construction: these are deltas from THIS build's"
          "\n  full strength, so they stay meaningful when the engine gains. They"
          "\n  are NOT absolute Elo and NOT a progress instrument (limited engines"
          "\n  compress real differences ~5x -- see the module docstring).")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--levels", default="0,10,20,30",
                    help="comma-separated skill levels to calibrate")
    ap.add_argument("--positions", type=int, default=500,
                    help="match.py positions per level (x2 = games)")
    ap.add_argument("--fit", nargs="*", help="fit from finished logs instead")
    args = ap.parse_args()

    if args.fit is not None:
        logs = args.fit or glob.glob("skillcal_*.log")
        return fit(logs)

    levels = [int(x) for x in args.levels.split(",") if x.strip()]
    bad = [l for l in levels if not 0 <= l < 40]
    if bad:
        sys.exit(f"levels must be 0..39 (40 is full strength, the baseline): {bad}")
    made = write_shims(levels)
    print(f"wrote {len(made)} shim(s):")
    for p in made:
        print("   ", os.path.relpath(p, ROOT))
    print("\nRun these ONE AT A TIME (each is a full match; nothing is started "
          "for you):\n")
    for lv in levels:
        print(f"python3 match.py NNUE/shims/engine_skill{lv:02d}.py "
              f"NNUE/shims/engine_v61b_deadtag.py {args.positions} 0 "
              f"--workers $(($(nproc)/2)) --tc 10+0.1 --seed 59 "
              f"2>&1 | tee skillcal_skill{lv:02d}.log")
        print()
    print("Then:  python3 scripts/calibrate_skill.py --fit")


if __name__ == "__main__":
    main()
